on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

      upload_url:
        required: true
        type: string

      release_ref:
        required: true
        type: string

      overwrite:
        required: true
        type: boolean

      release_name:
        required: false
        type: string
      
      release_body:
        required: false
        type: string

jobs:
  linux-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --locked --verbose --release --target aarch64-unknown-linux-gnu
      env:
        OPENSSL_STATIC: 1

    - name: Create Release Archive
      shell: bash
      run: |
        mkdir staging
        cp "target/release/wally" staging/
        cd staging
        zip ../release.zip *

    - name: Upload Archive to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.tag }}
        file: release.zip
        asset_name: wally-${{ inputs.release_ref }}-linux-arm64.zip
        overwrite: ${{ inputs.overwrite }}
        release_name: ${{ inputs.release_name }}
        body: ${{ inputs.release_body }}
        prerelease: true

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --locked --verbose --release
      env:
        OPENSSL_STATIC: 1

    - name: Create Release Archive
      shell: bash
      run: |
        mkdir staging
        cp "target/release/wally" staging/
        cd staging
        zip ../release.zip *

    - name: Upload Archive to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.tag }}
        file: release.zip
        asset_name: wally-${{ inputs.release_ref }}-linux.zip
        overwrite: ${{ inputs.overwrite }}
        release_name: ${{ inputs.release_name }}
        body: ${{ inputs.release_body }}
        prerelease: true
