name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: comnoco/create-release@v2        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    uses: ./.github/workflows/build.yml
    needs: create-release
    with:
      tag: ${{ github.ref_name }}
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      release_ref: ${{ github.ref_name }}
      overwrite: false
